### ISSUE TITLE
Status of xTomlj as a fork

### ISSUE THREAD

**Issue by A248** [xtomlj/xtomlj#1]
I noticed you forked off from tomlj and even published to Maven Central. I'm wondering what your development policy is. I have some PRs to the inactive tomlj and I was thinking about contributing them to xtomlj. Also, I may want to use xtomlj in a dependent library.

Will you continue to add new features, or is this mostly a maintenance fork? Do you consider xtomlj a dependable library, and will you maintain it for years to come? These are the important questions.

One feature in particular which would be useful is the ability to write comments. This would allow some downstream configuration libraries to use TOML to its fullest extent, via this toml library. If you'd like me to, I can open a new issue for it.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I forked this because the Tomlj library seems to be abandoned by the maintainer and I wanted to use it in dependent projects myself as soon as possible.

I already saw your PRs and wanted to merge them here. Even better if you would create PRs yourself.

I definitely want to add some features (one just has to take a look at the issue tracker of the original project) and will definitely be here to review further changes.

A difficult question is whether this library should compete with the original Tomlj.
Assuming that the original Tomlj remains inactive, this fork will be and will remain dependable.

It would be a different story if the maintainer came back in a short time (e.g. 2 weeks) and merged all the changes made here identically. 

Feel free to create another issue for your feature requirement and I'll take a look.

You are also welcome to ask further questions if anything is still unclear.

**Comment by A248** [comment]
That clarifies the situation a lot, thanks. I have just one more question then.

What will happen if the original Tomj becomes re-active but hasn't yet merged features, e.g. writing toml? I assume you will maintain this fork (at least with bug-fixes) until the features are merged into the original tomlj?

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
Yes, in that case I would continue to maintain it.

We don't even know if all of the changes made here would be fully merged, so it might make sense to continue to maintain this as a competitor.

**Comment by guilhermesgb** [comment]
I'd like to say I'm very happy that just stumbled upon your fork after looking for alternatives.

The original one has [https://github.com/tomlj/tomlj/issues/33][this bug] which for me is a complete deal breaker and I was happy to find that this use case is already supported by your fork.

Many thanks!

**Comment by cleishm** [comment]
I wouldn't necessarily call it abandoned if you haven't actually asked the maintainer more directly (e.g. via email). 😉

If you want to help TOMLJ, it's probably better to be a maintainer rather than fork it, no?

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I have archived this project and may contribute to the original project.
